version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: ubuntu-2204:2023.10.1
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/google* /etc/apt/sources.list.d/heroku*
      - run: ls -lh /etc/apt/sources.list.d/
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt update
      - run: sudo apt install ansible ansible-lint tree

      # prep
      - run: ansible --version
      - run: ansible-lint --version

      - checkout
      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      # dependencies
      - run: ansible-galaxy collection list

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      # debug
      - run:
          command: cat /etc/default/velocity
          when: always
      - run:
          command: sudo journalctl --no-pager --unit=velocity
          when: always
      - run:
          command: sudo systemctl --no-pager -l status velocity
          when: always
      - run:
          command: sudo tree /home/velocity
          when: always

      - run: while ! sudo -u velocity screen -list velocity; do sleep 1; done
      - run: sleep 10
      - run: sudo -u velocity screen -p 0 -S velocity -X eval 'stuff "version"\015'
      - run: sleep 2

      - run:
          command: sudo cat /home/velocity/logs/latest.log
          when: always

      - run: sudo systemctl stop velocity
